### PR TITLE
Phpunit9

### PR DESCRIPTION
**Pull request by jstanden**
Please see the discussion in #107.

The current version-locked PHPUnit dependency uses the `each()` function, which has been removed in PHP 8.

This PR would work best if the `0.x` versions continue to support PHP 5.4 (if desirable), and a new `1.x` release line supports PHP 7.4 and 8.x.

The former PR (#108) just adds PHP 8.0 to the supported versions in Composer without updating these unit tests.

### CODE REVIEW

**Comment by singpolyma** [comment]
I am ok to support only PHP 7.3+ going forward.  I would not like to gratuitously break backward compatibility for older versions in the library, but for the test and CI I am ok to move to 7.3+ only.  Please update the travis config in this PR to remove pre-7.3 versions and also to start testing newer versions (travis currently is only testing up to 7.4).  Once travis passes 7.3-8.0 I will merge this PR.

Thanks!

**Comment by jstanden** [comment]
👍 Thanks! I'm on it.

**Comment by jstanden** [comment]
I modified `.travis.dhall` and used `dhall-to-yaml-ng` to build the new `.travis.yml`. I'm verifying the new tests on TravisCI from my fork now. I'll report back shortly.

**Comment by jstanden** [comment]
I had to update the Travis build file to use Ubuntu Xenial (16.04) rather than Trusty (14.04), since the latter doesn't have a PHP 8.0 package. Since tests are running on PHP 7.3+ now, Ubuntu could probably be bumped up to Bionic (18.04) or Focal (20.04). I just followed convention and used the oldest one that supported all versions.

I'm re-running those last few tests and we should be good.

**Comment by jstanden** [comment]
Alright, all the tests pass in Travis with PHP 7.3, 7.4, and 8.0.

**Pull request merged**
