### PR TITLE
Update keygen.php

### PR DESCRIPTION
**Pull request by cgraefe**
This is what I think should fix issue #38.

### CODE REVIEW

**Comment by singpolyma** [comment]
Since you're the original reporter of the issue, I assume this fixes for you locally?

**Comment by cgraefe** [comment]
Yes, it does for me. 
And I'm sorry that I opened 2 issues for this, I did not mean to. Sometimes Github is beyond me...

**Comment by singpolyma** [comment]
based on the test failures, this appears to be a change in newer versions of phpseclib.  So will need to detect if the structure is the old one or new one and switch, so that multiple phpseclib versions can be supported.

**Comment by singpolyma** [comment]
If you look at https://github.com/singpolyma/openpgp-php/blob/752d80f14a39a79b1abcf7267c3adb59c792cba3/lib/openpgp.php#L1335 constructing a public key from another public key (or subclass, like secret key) should definitely work.  If you're still having this problem with latest master please update #38 with a backtrace so I can investigate what is going wrong.  I still cannot reproduce locally.

**Pull request closed without merging**
